context:
  name: font-ttf-ibm-plex-sans
  version: "1.1.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/IBM/plex/releases/download/%40ibm%2Fplex-sans%40${{ version }}/ibm-plex-sans.zip
  sha256: fb365d910566e6d199cc2c15579a7dd9a267128e18431a394ed81f1970c69200

build:
  number: 0
  noarch: generic
  script:
    - mkdir -p $PREFIX/fonts
    - install -v -m644 fonts/complete/ttf/*.ttf $PREFIX/fonts/

requirements:
  build:
    - __unix

tests:
  - package_contents:
      files:
        - fonts/IBMPlexSans-Bold.ttf
        - fonts/IBMPlexSans-BoldItalic.ttf
        - fonts/IBMPlexSans-ExtraLight.ttf
        - fonts/IBMPlexSans-ExtraLightItalic.ttf
        - fonts/IBMPlexSans-Italic.ttf
        - fonts/IBMPlexSans-Light.ttf
        - fonts/IBMPlexSans-LightItalic.ttf
        - fonts/IBMPlexSans-Medium.ttf
        - fonts/IBMPlexSans-MediumItalic.ttf
        - fonts/IBMPlexSans-Regular.ttf
        - fonts/IBMPlexSans-SemiBold.ttf
        - fonts/IBMPlexSans-SemiBoldItalic.ttf
        - fonts/IBMPlexSans-Text.ttf
        - fonts/IBMPlexSans-TextItalic.ttf
        - fonts/IBMPlexSans-Thin.ttf
        - fonts/IBMPlexSans-ThinItalic.ttf

about:
  homepage: https://www.ibm.com/plex/
  summary: 'IBM Plex typeface'
  description: |
    The IBM Plex typeface is an open-source project available for download and
    various uses following the Open Font License (OFL). 
    The IBM Plex family comes in Sans, Serif, Mono, and Sans Condensed,
    all with Roman and true italics.
    Plex has been designed to work well in user interface (UI) environments and other mediums.
  license: OFL-1.1
  license_file: LICENSE.txt
  repository: https://github.com/IBM/plex

extra:
  recipe-maintainers:
    - Hofer-Julian
